[options]
Architecture = auto
CheckSpace
SigLevel = Never

[core]
Server = https://mirror.yandex.ru/archlinux/$repo/os/$arch

[extra]
Server = https://mirror.yandex.ru/archlinux/$repo/os/$arch

[multilib]
Server = https://mirror.yandex.ru/archlinux/$repo/os/$arch
